### ISSUE TITLE
Daikinapi gets stuck in fan mode

### ISSUE THREAD

**Issue by w4935057** [arska/python-daikinapi#11]
When mode differs from 6 (Fan) the API can be used to switch between modes at will.
When mode 6 (Fan) is selected it becomes impossible to change mode with through the API.
Mode can only be change by using the DaikinAndroid app or the remote control.
Attached fantest.zip contains a python3 test program to reproduce the issue an the output of a test run on 4 different powered down units. After the run all units are in fan mode.
[fantest.zip](https://github.com/arska/python-daikinapi/files/9189951/fantest.zip)
The unit firmware version is 1.2.54

**Comment by arska** [comment]
Hello @w4935057, thanks for reporting! Might this be related to #1 ? I'm happy to merge a pull request if you can figure out what needs to be sent to the API to get the device to change fan speeds after 6.
