### ISSUE TITLE
Daikinapi: BRP069A41 and BRP069B41: time-out

### ISSUE THREAD

**Issue by ed41007** [arska/python-daikinapi#12]
Art home iam using Daikin modules BRP069A41 and BRP069B41.
Trying to connect via Python-daikinapi.
But the connection fails: time-out

message:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python311-32\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Program Files (x86)\Python311-32\Lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Program Files (x86)\Python311-32\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Een verbindingspoging is mislukt omdat de verbonden party niet correct heeft geantwoord na een bepaalde tijd, of de gemaakte verbinding is mislukt omdat de verbonden host niet heeft geantwoord

**Comment by gjdv** [comment]
Could it be that you have the Daikin app installed (on phone/tablet) and that it is keeping a connection open to the Daikin devices? I noticed that I cannot connect via the api when the (android) app has an established connection open. When I disconnect the android device from the network (and thus ensure it doesn't have a connection open anymore), I can connect again from my pc.

**Comment by arska** [comment]
Hello @ed41007, have you tried @gjdv suggestion? The error message means for me a connection was not possible to the device, so probably nothing we can solve in our code. Closing
