### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by sharkwsk** [arska/python-daikinapi#13]
Hi @arska,

I am trying to test the example.py script against my Daikin WiFi controller, unfortunately getting below erro

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.1.103/aircon/get_control_info`

When I paste the URL in my browser, I get a similar error
`ret=PARAM NG,msg=404 Not Found`

BR,
Sshark

**Comment by arska** [comment]
Hello @sharkwsk, do the other API calls like basic_info return any information? If not, it might be a newer (cloud) wifi module that has a different API.
