### ISSUE TITLE
Compatibility with cloud wifi module BRP069C4x

### ISSUE THREAD

**Issue by Archimonde666** [arska/python-daikinapi#6]
Hello there, 

I just installed a brand new FTXM with wifi. working fine with the cloud applicant but i wanna retrieve the data to process and control it inside my home server.
When i connect directly to the local adress i only get a text licence page with the included open sources but no other "open" web api.

When i try to connect it with your python example, i get a 404 error on https://IP/common/basic_info
I also tried to access that endpoint from a browser in both http and https. But i still get a 404 response from the daikin.

tested with daikin firmware 1_1_30 AND 1_12_30 both seems not to work with this package.
I'm open about contributing if it's needed for that package to work for my setup :p

**Comment by jdarmetzki** [comment]
I have an older FTXM with separate wifi-module that i had to upgrade to FW 1_14_28 and that now works with the Daikin redidential app (https://play.google.com/store/apps/details?id=com.daikineurope.online.controller&hl=de&gl=US). This unit still responds to the HTTP-Api. 

However, one of my indoor units was swapped for a FTXM-R under warranty. This unit has integrated WIFI and will not work with the classic HTTP-Api. From what i gathered this currently only works via Daikins Cloud-API which is also not officially available to 3rd parties. 

(EU-Market by the way. From what i could see in the FW, JP should be _very_ different)

**Comment by Archimonde666** [comment]
yeah actually i did further investigations and the problem is the wifi cloud module (BRP069C4x) that is working differently, see https://github.com/cbrandlehner/homebridge-daikin-local/issues/123
and it's not supporting direct local API call unless we trick daiking and retrieve a token

**Comment by arska** [comment]
As I don't have a device with cloud wifi module there's not so much I can contribute. If you're interested to work on this I'm happy to review and merge and I'll leave this open as "enhancement". If you can't work on this either then I'll close this.
